# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chadanui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(305, 170)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 62, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dan_info_title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dan_info_title.setObjectName("dan_info_title")
        self.gridLayout.addWidget(self.dan_info_title, 1, 0, 1, 1)
        self.dan_statu_title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dan_statu_title.setObjectName("dan_statu_title")
        self.gridLayout.addWidget(self.dan_statu_title, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(71, 90, 211, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dan_statu = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dan_statu.setObjectName("dan_statu")
        self.verticalLayout.addWidget(self.dan_statu)
        self.dan_info_phone = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dan_info_phone.setObjectName("dan_info_phone")
        self.verticalLayout.addWidget(self.dan_info_phone)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dan_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dan_lineEdit.setObjectName("dan_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dan_lineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_mobile = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_mobile.setEnabled(True)
        self.checkBox_mobile.setChecked(True)
        self.checkBox_mobile.setObjectName("checkBox_mobile")
        self.horizontalLayout_2.addWidget(self.checkBox_mobile)
        self.checkBox_unicom = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_unicom.setChecked(True)
        self.checkBox_unicom.setObjectName("checkBox_unicom")
        self.horizontalLayout_2.addWidget(self.checkBox_unicom)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(177, 10, 111, 51))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.status_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.status_label.setObjectName("status_label")
        self.gridLayout_5.addWidget(self.status_label, 1, 0, 1, 1)
        self.cash_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.cash_label.setObjectName("cash_label")
        self.gridLayout_5.addWidget(self.cash_label, 2, 0, 1, 1)
        self.status = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.status.setObjectName("status")
        self.gridLayout_5.addWidget(self.status, 1, 1, 1, 1)
        self.cash = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.cash.setObjectName("cash")
        self.gridLayout_5.addWidget(self.cash, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 281, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gridLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.Button_commit = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Button_commit.setObjectName("Button_commit")
        self.horizontalLayout.addWidget(self.Button_commit)
        self.Button_get_cash = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Button_get_cash.setObjectName("Button_get_cash")
        self.horizontalLayout.addWidget(self.Button_get_cash)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dan_info_title.setText(_translate("Dialog", "订单信息："))
        self.dan_statu_title.setText(_translate("Dialog", "获取状态："))
        self.dan_statu.setText(_translate("Dialog", "未启动"))
        self.dan_info_phone.setText(_translate("Dialog", "null"))
        self.label_4.setText(_translate("Dialog", "面额"))
        self.checkBox_mobile.setText(_translate("Dialog", "移动"))
        self.checkBox_unicom.setText(_translate("Dialog", "联通"))
        self.status_label.setText(_translate("Dialog", "登录状态："))
        self.cash_label.setText(_translate("Dialog", "账户金额："))
        self.status.setText(_translate("Dialog", "离线"))
        self.cash.setText(_translate("Dialog", "0"))
        self.startButton.setText(_translate("Dialog", "开始"))
        self.stopButton.setText(_translate("Dialog", "停止"))
        self.Button_commit.setText(_translate("Dialog", "提交"))
        self.Button_get_cash.setText(_translate("Dialog", "提现"))

